### ISSUE TITLE
Setting JTorSocketFactoryImpl results into dead lock

### ISSUE THREAD

**Issue by n0rbyt3** [subgraph/Orchid#2]
Hey,

I'm new to github and I'm very interested in this project. I tried to set the SocketImpleFactory by this little script:

TorClient client = new TorClient();
client.start();
Socket.setSocketImplFactory(new JTorSocketImplFactory(client));

Unfortunately, it hangs. The problem is in "ConnectionImpl:connectSocket()". Here, a new Socket will be opened to init Tor, but it uses the "JTorSocketImpl" class instead of the original one. "TorClient:start" should block, until a circuit is created, but I don't know, how to do this the best way.

**Comment by n0rbyt3** [comment]
I implementated a "waitUntilReady" function like this:

edit TorClient.java:
- at the end of start method insert:

``` java
StartBlockingInitializationListener listener = new StartBlockingInitializationListener();
initializationTracker.addListener(listener);
synchronized (listener) {
  try {
    listener.wait();
  } catch (InterruptedException e) {
    // TODO handle
  }
}
```
- at the end of class insert:

``` java
private static class StartBlockingInitializationListener implements TorInitializationListener {

  public void initializationProgress(String message, int percent) {
  }

  public void initializationCompleted() {
    synchronized (this) {
      notifyAll();
    }
  }
}
```

**Comment by brl** [comment]
You should poll on a boolean variable:

``` java
synchronized(lock) {
    while(!isReady) {
        lock.wait();
    }
}
```

With your current implementation, if you are unlucky the notifyAll() can fire after addListener(), but before entering the synchronized block.

**Comment by brl** [comment]
I added this for you:

ef91ca99ba6641e5fdc2df00ea92521156618d8e

**Comment by n0rbyt3** [comment]
You're right, thanks for your implementation! :)

**Comment by brl** [comment]
oops, I didn't get it right the first time either:

dbecc8acc838b60e03b0301ef22413085a5c06f2

**Comment by brl** [comment]
The JtorSocketImplFactory class should be removed since nothing is currently using it and as you found out it doesn't work if you try to use it to replace the SocketImplFactory in Socket.  The socket factory code was written recently for the single purpose of supporting the JTor custom xml-rpc transport classes (which are in the /opt directory) for a user who wants to use JTor with the Apache xml-rpc library.

If you are planning on using JTor by embedding it as a library rather than using the SOCKS proxy, you should know that I'm actively developing JTor right now and many things are being refactored which might include the API for creating new streams.  In particular, OpenStreamResponse is probably going away to be replaced by simply returning a Stream or throwing a TimeoutException:

Old:

``` java
public OpenStreamResponse openExitStreamTo(String hostname, int port) throws InterruptedException
```

New:

``` java
public Stream openExitStreamTo(String hostname, int port) throws InterruptedException, TimeoutException
```

**Comment by n0rbyt3** [comment]
I'm actually looking for a java implementation of Tor. My goal is to redirect all socket calls to Tor like silvertunnels NetLib. But that library doesn't work, because it's too slow and the support is not helpful. Now I ended up with JTor. Small, fast, working (!!!) and with its own SocketFactoryImpl. JTor is exactly, what I was looking for and its nice to see the active development.

So please keep in mind that a SocketFactory implementation is very useful if you can't set a proxy manually. And tor should interact like an invisible tunnel. It works now with the following code:

``` java
TorClient client = new TorClient();
client.start();
client.waitUntilReady();
Socket.setSocketImplFactory(new JTorSocketImplFactory(client));
```

Refactoring is no problem for me. I'm currently using TorClient only. Great job, brl!

**Comment by brl** [comment]
That will only work until JTor needs to open another socket, right?

**Comment by brl** [comment]
I'll take a closer look at what Silvertunnel is doing, but I'm skeptical about supporting that approach for a number of reasons.

**Comment by n0rbyt3** [comment]
It works after adding the "waitUntilReady" call. Silvertunnel offers a test page: http://httptest.silvertunnel.org/httptest/bigtest.jsp which returns request headers and client ip. I used this to verify that tor is active. The simple code for that is:

``` java
URL url = new URL("http", "httptest.silvertunnel.org", 80, "/httptest/bigtest.jsp");
URLConnection conn = url.openConnection();
conn.setDoInput(true);
BufferedReader reader = new BufferedReader(new InputStreamReader(conn.getInputStream()));
String line;
while ((line = reader.readLine()) != null) {
  System.out.println(line);
}
reader.close();
```

Without setting SocketImplFactory it returns my real ip, after setting the factory (URLConnection uses socket internally) a foreign ip is shown. Everything works fine for me. But I don't know what happens if new circuits will be created.

I'll try to include JTor into my project and do some more tests.

**Comment by n0rbyt3** [comment]
I think this code might be interested (taken from Silvertunnel NetLib):

``` java
/**
     * Create a new Socket with the JDK built-in SocketImpl.
     * 
     * The result does not use/depend on a SocketImplFactory set in class Socket.
     *  
     * @return a new (Extended)Socket, as it would be created with new Socket() with unset SocketImplFactory
     * @throws RuntimeException if the socket could not be created 
     */
    @SuppressWarnings("unchecked")
    public static ExtendedSocket createOriginalSocket() throws RuntimeException {
        if (log.isLoggable(Level.FINER)) {
            log.log(Level.FINER, "createOriginalSocket() called here:", new Throwable("stacktrace for debugging - not an error"));
        }

        if (netlibSocketImplFactory==null) {
            // SocketImplFactory not yet set (by this class) in class Socket:
            // use default code
            return new ExtendedSocket();
        } else {
            // SocketImplFactory set in class Socket:
            // use specific special and maybe unportable code

            // 1st attempt,
            // this solution works for Java 1.6, but it does break security restrictions:
            try {
                Class clazz = Class.forName("java.net.SocksSocketImpl");
                Constructor constructor = clazz.getDeclaredConstructor();
                // this maybe does not work because of security restrictions:
                constructor.setAccessible(true);
                SocketImpl impl = (SocketImpl)constructor.newInstance();
                return new ExtendedSocket(impl);

            } catch (Throwable t1) {
                String msg = "createOriginalSocket()#1st attempt: could not create a Socket for Java Version: "+JavaVersion.getJavaVersion();
                log.log(Level.SEVERE, msg, t1);

                // 2nd attempt,
                // this solution doen't work for Java 1.6, but it does not break security restrictions:
                try {
                    return new ExtendedSocket(new PatchedProxy());

                } catch (Throwable t2) {
                    msg = "createOriginalSocket()#2nd attempt: could not create a Socket for Java Version: "+JavaVersion.getJavaVersion();
                    log.log(Level.SEVERE, msg+", "+t2);

                    throw new RuntimeException(msg+", "+t2);
                }
            }
        }
    }
```

Seems to be quiet a hack but may resolve the issue.

``` java
/**
 * 
 * See class SocketUtil
 * 
 * @author hapke
 */
class PatchedProxy extends Proxy {
    private static final int SOCKS_DEFAULT_PORT = 1080;

    public PatchedProxy() {
         // address any port at any local address
        super(Type.SOCKS, new InetSocketAddress((InetAddress)null, SOCKS_DEFAULT_PORT));
    }

    /**
     * This method is called from
     *     java.net.Socket.Socket(Proxy proxy) to check the proxy address:
     *     return the ordinary address of this object of type InetSocketAddress
     * and from
     *     java.net.SocksSocketImpl.SocksSocketImpl(Proxy proxy) to determine the implementation details:
     *     return an object that is not of type InetSocketAddress
     */
    @Override
    public SocketAddress address() {
        // determine the calling class
        StackTraceElement[] elements = new Exception().getStackTrace();
        String callingClassFullName = elements[1].getClassName();

        final String SOCKS_COCKET_IMPL = "java.net.SocksSocketImpl";

        if (!SOCKS_COCKET_IMPL.equals(callingClassFullName)) {
             // called from java.net.Socket.Socket(Proxy proxy) to check the proxy address (or from somewhere else)
            return super.address();
        } else {
            // called from java.net.SocksSocketImpl.SocksSocketImpl(Proxy proxy) to determine the implementation details
            return new InvalidSocketAddress();
        }
    }

}
```
